"""add login rate limit source hash

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs", sa.Column("client_ip_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_audit_logs_client_ip_hash"),
        "audit_logs",
        ["client_ip_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_client_ip_hash"), table_name="audit_logs")
    op.drop_column("audit_logs", "client_ip_hash")
    # ### end Alembic commands ###
